# Generated by Django 4.2.5 on 2023-09-25 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devisa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoas',
            name='cadatradoPor',
            field=models.CharField(max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='pessoas',
            name='cpf',
            field=models.CharField(max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='pessoas',
            name='dataDeNascimento',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='pessoas',
            name='dataDoCadastro',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='pessoas',
            name='dataUltimaAtualizacao',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='pessoas',
            name='endereco',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='pessoas',
            name='nomeDaMae',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pessoas',
            name='observacao',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='ativo',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='perfil',
            field=models.CharField(choices=[('1', 'Administrador'), ('2', 'Coordenador'), ('3', 'Digitador')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='senha',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pessoas',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pessoas',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('I', 'Ignorado')], max_length=1),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='celular',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
