# Generated by Django 4.2.5 on 2023-09-25 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devisa', '0002_pessoas_cadatradopor_pessoas_cpf_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Doencas',
            new_name='Doenca',
        ),
        migrations.RenameModel(
            old_name='Pessoas',
            new_name='Pessoa',
        ),
        migrations.RenameModel(
            old_name='Usuarios',
            new_name='Usuario',
        ),
    ]
