# Generated by Django 4.2.5 on 2023-09-25 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devisa', '0003_rename_doencas_doenca_rename_pessoas_pessoa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='cadatradoPor',
            field=models.CharField(default='', max_length=14),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='cpf',
            field=models.CharField(default='', max_length=14),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='dataDeNascimento',
            field=models.DateField(default='2000-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='dataDoCadastro',
            field=models.DateField(auto_now_add=True, default='2000-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='dataUltimaAtualizacao',
            field=models.DateField(auto_now=True, default='2000-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='endereco',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='nomeDaMae',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='observacao',
            field=models.CharField(default='', max_length=600),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='ativo',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='perfil',
            field=models.CharField(choices=[('1', 'Administrador'), ('2', 'Coordenador'), ('3', 'Digitador')], default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='senha',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
