# Generated by Django 4.2.5 on 2023-09-25 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devisa', '0004_alter_pessoa_cadatradopor_alter_pessoa_cpf_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pessoa',
            old_name='cadatradoPor',
            new_name='cadastradoPor',
        ),
    ]
