# Generated by Django 4.2.5 on 2023-09-27 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devisa', '0006_alter_pessoa_cpf_alter_pessoa_datadenascimento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='dataDeNascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='endereco',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='observacao',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
